name: Arduino Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v2
  
      with:
        arduino-version: latest

    - name: Install necessary libraries
      run: |
        arduino-cli lib install "sparkfun/MMA8452_Accelerometer"
        arduino-cli lib install "arduino/wire"
        # Add other libraries as needed

    - name: Compile sketches
      run: |
        arduino-cli compile --fqbn arduino:avr:micro .
