name: Arduino Build and Upload

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Arduino CLI
      uses: per1234/setup-arduino-cli@v2
      with:
        arduino-cli-version: '0.18.3'

    - name: Install board support
      run: arduino-cli core install arduino:avr

    - name: Install library dependencies
      run: arduino-cli lib install SparkFun_MMA8452Q_Arduino_Library

    - name: Compile sketch
      run: arduino-cli compile --fqbn arduino:avr:micro .

    - name: Upload sketch
      run: arduino-cli upload -p /dev/ttyACM0 --fqbn arduino:avr:micro .
