name: TestCompile
on: push
jobs:
  build:
    name: Test compiling examples for UNO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
          sketch-names: acc-logger.ino
          
      - name: Checkout custom library
        uses: actions/checkout@v2
        with:
          repository: sparkfun/SparkFun_MMA8452Q_Arduino_Library/src 
          ref: master
          path: CustomLibrary # must contain string "Custom"
