name: Arduino Build und Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v2

    - name: Arduino CLI einrichten
      uses: arduino/setup-arduino-cli@v2

    - name: Board-Support installieren
      run: arduino-cli core install arduino:avr

    - name: Bibliotheksabhängigkeiten installieren
      run: arduino-cli lib install SparkFun_MMA8452Q_Arduino_Library

    - name: Sketch kompilieren
      run: arduino-cli compile --fqbn arduino:avr:micro .

    - name: Sketch hochladen
      run: arduino-cli upload -p /dev/ttyACM0 --fqbn arduino:avr:micro .
